#!/bin/bash
# 对比源仓库和企业版的 gendoc 差异

echo "=== gendoc 工具差异对比 ==="
echo ""
echo "📌 关键配置差异："
echo ""
echo "| 配置项 | terraform-provider-tencent | terraform-provider-tencentcloudenterprise |"
echo "|--------|----------------------------|------------------------------------------|"
echo "| cloudMark | cloud | tencentcloudenterprise |"
echo "| cloudTitle | TencentCloud | TencentCloudEnterprise |"
echo "| cloudPrefix | cloud_ | tencentcloudenterprise_ |"
echo "| docRoot | ../website/docs | ../docs |"
echo "| 文档扩展名 | .html.markdown | .md |"
echo "| 数据源目录 | data_source | data-sources |"
echo "| 资源目录 | resource | resources |"
echo ""
echo "📁 目录结构对比："
echo ""
echo "terraform-provider-tencent:"
echo "  └── website/"
echo "      ├── cloud.erb"
echo "      └── docs/"
echo "          ├── data_source/"
echo "          │   └── cloud_*.html.markdown"
echo "          └── resource/"
echo "              └── cloud_*.html.markdown"
echo ""
echo "terraform-provider-tencentcloudenterprise:"
echo "  └── docs/"
echo "      ├── index.md"
echo "      ├── data-sources/"
echo "      │   └── tencentcloudenterprise_*.md"
echo "      └── resources/"
echo "          └── tencentcloudenterprise_*.md"
echo ""
echo "✨ 适配说明："
echo ""
echo "1. ✅ 更新了所有常量以匹配企业版命名"
echo "2. ✅ 修改了文档输出路径（docs/ 而非 website/docs/）"
echo "3. ✅ 修改了文档扩展名（.md 而非 .html.markdown）"
echo "4. ✅ 修改了子目录名称（data-sources/ 和 resources/）"
echo "5. ✅ 修改了索引文件名（index.md 而非 cloud.erb）"
echo "6. ✅ 保留了所有核心功能（Schema 解析、格式验证、HCL 格式化）"
echo "7. ✅ 添加了依赖管理（go.mod 包含 fatih/color）"
echo ""
echo "🎯 使用方式："
echo ""
echo "  cd terraform-provider-tencentcloudenterprise/gendoc"
echo "  ./generate.sh"
echo ""
echo "或者："
echo ""
echo "  cd terraform-provider-tencentcloudenterprise/gendoc"
echo "  go run *.go"
echo ""
