// Code generated by yunapi-go-generator. DO NOT EDIT.

package v20250312

import (
	"terraform-provider-tencentcloudenterprise/sdk/common"
	tchttp "terraform-provider-tencentcloudenterprise/sdk/common/http"
	"terraform-provider-tencentcloudenterprise/sdk/common/profile"
)

const APIVersion = "2025-03-12"

var _ = tchttp.POST

type Client struct {
	common.Client
}

// Deprecated
func NewClientWithSecretId(secretId, secretKey, region string) (client *Client, err error) {
	cpf := profile.NewClientProfile()
	client = &Client{}
	client.Init(region).WithSecretId(secretId, secretKey).WithProfile(cpf)
	return
}

func NewClient(credential *common.Credential, region string, clientProfile *profile.ClientProfile) (client *Client, err error) {
	client = &Client{}
	client.Init(region).
		WithCredential(credential).
		WithProfile(clientProfile)
	return
}

func NewCreateVpnGatewaySslClientRequest() (request *CreateVpnGatewaySslClientRequest) {
	request = &CreateVpnGatewaySslClientRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "CreateVpnGatewaySslClient")
	return
}

func NewCreateVpnGatewaySslClientResponse() (response *CreateVpnGatewaySslClientResponse) {
	response = &CreateVpnGatewaySslClientResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 创建SSL-VPN-CLIENT
func (c *Client) CreateVpnGatewaySslClient(request *CreateVpnGatewaySslClientRequest) (response *CreateVpnGatewaySslClientResponse, err error) {
	if request == nil {
		request = NewCreateVpnGatewaySslClientRequest()
	}
	response = NewCreateVpnGatewaySslClientResponse()
	err = c.Send(request, response)
	return
}

func NewCreateVpnGatewaySslServerRequest() (request *CreateVpnGatewaySslServerRequest) {
	request = &CreateVpnGatewaySslServerRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "CreateVpnGatewaySslServer")
	return
}

func NewCreateVpnGatewaySslServerResponse() (response *CreateVpnGatewaySslServerResponse) {
	response = &CreateVpnGatewaySslServerResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 本接口（CreateVpnGatewaySslServer）用于创建SSL-VPN Server端。
func (c *Client) CreateVpnGatewaySslServer(request *CreateVpnGatewaySslServerRequest) (response *CreateVpnGatewaySslServerResponse, err error) {
	if request == nil {
		request = NewCreateVpnGatewaySslServerRequest()
	}
	response = NewCreateVpnGatewaySslServerResponse()
	err = c.Send(request, response)
	return
}

func NewDeleteVpnGatewaySslClientRequest() (request *DeleteVpnGatewaySslClientRequest) {
	request = &DeleteVpnGatewaySslClientRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "DeleteVpnGatewaySslClient")
	return
}

func NewDeleteVpnGatewaySslClientResponse() (response *DeleteVpnGatewaySslClientResponse) {
	response = &DeleteVpnGatewaySslClientResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 本接口（DeleteVpnGatewaySslClient）用于删除SSL-VPN-CLIENT。
func (c *Client) DeleteVpnGatewaySslClient(request *DeleteVpnGatewaySslClientRequest) (response *DeleteVpnGatewaySslClientResponse, err error) {
	if request == nil {
		request = NewDeleteVpnGatewaySslClientRequest()
	}
	response = NewDeleteVpnGatewaySslClientResponse()
	err = c.Send(request, response)
	return
}

func NewDeleteVpnGatewaySslServerRequest() (request *DeleteVpnGatewaySslServerRequest) {
	request = &DeleteVpnGatewaySslServerRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "DeleteVpnGatewaySslServer")
	return
}

func NewDeleteVpnGatewaySslServerResponse() (response *DeleteVpnGatewaySslServerResponse) {
	response = &DeleteVpnGatewaySslServerResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 删除SSL-VPN-SERVER 实例
func (c *Client) DeleteVpnGatewaySslServer(request *DeleteVpnGatewaySslServerRequest) (response *DeleteVpnGatewaySslServerResponse, err error) {
	if request == nil {
		request = NewDeleteVpnGatewaySslServerRequest()
	}
	response = NewDeleteVpnGatewaySslServerResponse()
	err = c.Send(request, response)
	return
}

func NewDescribeVpnGatewaySslClientsRequest() (request *DescribeVpnGatewaySslClientsRequest) {
	request = &DescribeVpnGatewaySslClientsRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "DescribeVpnGatewaySslClients")
	return
}

func NewDescribeVpnGatewaySslClientsResponse() (response *DescribeVpnGatewaySslClientsResponse) {
	response = &DescribeVpnGatewaySslClientsResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 本接口（DescribeVpnGatewaySslClients）用于查询SSL-VPN-CLIENT 列表。
func (c *Client) DescribeVpnGatewaySslClients(request *DescribeVpnGatewaySslClientsRequest) (response *DescribeVpnGatewaySslClientsResponse, err error) {
	if request == nil {
		request = NewDescribeVpnGatewaySslClientsRequest()
	}
	response = NewDescribeVpnGatewaySslClientsResponse()
	err = c.Send(request, response)
	return
}

func NewDescribeVpnGatewaySslServersRequest() (request *DescribeVpnGatewaySslServersRequest) {
	request = &DescribeVpnGatewaySslServersRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "DescribeVpnGatewaySslServers")
	return
}

func NewDescribeVpnGatewaySslServersResponse() (response *DescribeVpnGatewaySslServersResponse) {
	response = &DescribeVpnGatewaySslServersResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 本接口（DescribeVpnGatewaySslServers）用于查询SSL-VPN SERVER 列表信息。
func (c *Client) DescribeVpnGatewaySslServers(request *DescribeVpnGatewaySslServersRequest) (response *DescribeVpnGatewaySslServersResponse, err error) {
	if request == nil {
		request = NewDescribeVpnGatewaySslServersRequest()
	}
	response = NewDescribeVpnGatewaySslServersResponse()
	err = c.Send(request, response)
	return
}

func NewDisableVpnGatewaySslClientCertRequest() (request *DisableVpnGatewaySslClientCertRequest) {
	request = &DisableVpnGatewaySslClientCertRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "DisableVpnGatewaySslClientCert")
	return
}

func NewDisableVpnGatewaySslClientCertResponse() (response *DisableVpnGatewaySslClientCertResponse) {
	response = &DisableVpnGatewaySslClientCertResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 禁用SSL-VPN-CLIENT 证书
func (c *Client) DisableVpnGatewaySslClientCert(request *DisableVpnGatewaySslClientCertRequest) (response *DisableVpnGatewaySslClientCertResponse, err error) {
	if request == nil {
		request = NewDisableVpnGatewaySslClientCertRequest()
	}
	response = NewDisableVpnGatewaySslClientCertResponse()
	err = c.Send(request, response)
	return
}

func NewDownloadVpnGatewaySslClientCertRequest() (request *DownloadVpnGatewaySslClientCertRequest) {
	request = &DownloadVpnGatewaySslClientCertRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "DownloadVpnGatewaySslClientCert")
	return
}

func NewDownloadVpnGatewaySslClientCertResponse() (response *DownloadVpnGatewaySslClientCertResponse) {
	response = &DownloadVpnGatewaySslClientCertResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 本接口（DownloadVpnGatewaySslClientCert）用于下载SSL-VPN-CLIENT 客户端证书。
func (c *Client) DownloadVpnGatewaySslClientCert(request *DownloadVpnGatewaySslClientCertRequest) (response *DownloadVpnGatewaySslClientCertResponse, err error) {
	if request == nil {
		request = NewDownloadVpnGatewaySslClientCertRequest()
	}
	response = NewDownloadVpnGatewaySslClientCertResponse()
	err = c.Send(request, response)
	return
}

func NewEnableVpnGatewaySslClientCertRequest() (request *EnableVpnGatewaySslClientCertRequest) {
	request = &EnableVpnGatewaySslClientCertRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "EnableVpnGatewaySslClientCert")
	return
}

func NewEnableVpnGatewaySslClientCertResponse() (response *EnableVpnGatewaySslClientCertResponse) {
	response = &EnableVpnGatewaySslClientCertResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 本接口（EnableVpnGatewaySslClientCert）用于启用SSL-VPN-CLIENT 证书。
func (c *Client) EnableVpnGatewaySslClientCert(request *EnableVpnGatewaySslClientCertRequest) (response *EnableVpnGatewaySslClientCertResponse, err error) {
	if request == nil {
		request = NewEnableVpnGatewaySslClientCertRequest()
	}
	response = NewEnableVpnGatewaySslClientCertResponse()
	err = c.Send(request, response)
	return
}

func NewModifyVpnGatewaySslClientRequest() (request *ModifyVpnGatewaySslClientRequest) {
	request = &ModifyVpnGatewaySslClientRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "ModifyVpnGatewaySslClient")
	return
}

func NewModifyVpnGatewaySslClientResponse() (response *ModifyVpnGatewaySslClientResponse) {
	response = &ModifyVpnGatewaySslClientResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 修改SSL-VPN-CLIENT属性
func (c *Client) ModifyVpnGatewaySslClient(request *ModifyVpnGatewaySslClientRequest) (response *ModifyVpnGatewaySslClientResponse, err error) {
	if request == nil {
		request = NewModifyVpnGatewaySslClientRequest()
	}
	response = NewModifyVpnGatewaySslClientResponse()
	err = c.Send(request, response)
	return
}

func NewModifyVpnGatewaySslServerRequest() (request *ModifyVpnGatewaySslServerRequest) {
	request = &ModifyVpnGatewaySslServerRequest{
		BaseRequest: &tchttp.BaseRequest{},
	}
	request.Init().WithApiInfo("vpc", APIVersion, "ModifyVpnGatewaySslServer")
	return
}

func NewModifyVpnGatewaySslServerResponse() (response *ModifyVpnGatewaySslServerResponse) {
	response = &ModifyVpnGatewaySslServerResponse{
		BaseResponse: &tchttp.BaseResponse{},
	}
	return
}

// 本接口用于修改 SSL-VPN 服务端属性
func (c *Client) ModifyVpnGatewaySslServer(request *ModifyVpnGatewaySslServerRequest) (response *ModifyVpnGatewaySslServerResponse, err error) {
	if request == nil {
		request = NewModifyVpnGatewaySslServerRequest()
	}
	response = NewModifyVpnGatewaySslServerResponse()
	err = c.Send(request, response)
	return
}
