// Code generated by yunapi-go-generator. DO NOT EDIT.

package v20250312

import (
	"encoding/json"

	tchttp "terraform-provider-tencentcloudenterprise/sdk/common/http"
)

var _ = tchttp.POST
var _ = json.Marshal

type AccessPolicy struct {

	// 是否对所有用户都生效。1 生效 0不生效

	ForAllClient *uint64 `json:"ForAllClient,omitempty" name:"ForAllClient"`
	// Remark

	Remark *string `json:"Remark,omitempty" name:"Remark"`
	// 目的CIDR

	TargetCidr *string `json:"TargetCidr,omitempty" name:"TargetCidr"`
	// 更新时间

	UpdateTime *string `json:"UpdateTime,omitempty" name:"UpdateTime"`
	// 用户组ID

	UserGroupIds []*string `json:"UserGroupIds,omitempty" name:"UserGroupIds"`
	// 策略ID

	VpnGatewayIdSslAccessPolicyId *string `json:"VpnGatewayIdSslAccessPolicyId,omitempty" name:"VpnGatewayIdSslAccessPolicyId"`
}

type Filter struct {

	// 属性名称, 若存在多个Filter时，Filter间的关系为逻辑与（AND）关系。

	Name *string `json:"Name,omitempty" name:"Name"`
	// 属性值, 若同一个Filter存在多个Values，同一Filter下Values间的关系为逻辑或（OR）关系。当值类型为布尔类型时，可直接取值为字符串"TRUE"或 "FALSE"。

	Values []*string `json:"Values,omitempty" name:"Values"`
}

type FilterObject struct {

	// 属性名称, 若存在多个Filter时，Filter间的关系为逻辑与（AND）关系。

	Name *string `json:"Name,omitempty" name:"Name"`
	// 属性值, 若同一个Filter存在多个Values，同一Filter下Values间的关系为逻辑或（OR）关系。

	Values []*string `json:"Values,omitempty" name:"Values"`
}

type SslClientConfig struct {

	// 客户端证书

	SslVpnCert *string `json:"SslVpnCert,omitempty" name:"SslVpnCert"`
	// 客户端配置

	SslVpnClientConfiguration *string `json:"SslVpnClientConfiguration,omitempty" name:"SslVpnClientConfiguration"`
	// SSL-VPN-CLIENT 实例ID。

	SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
	// 客户端密钥

	SslVpnKey *string `json:"SslVpnKey,omitempty" name:"SslVpnKey"`
	// 更证书

	SslVpnRootCert *string `json:"SslVpnRootCert,omitempty" name:"SslVpnRootCert"`
}

type SslVpnClient struct {

	// 证书开始时间。

	CertBeginTime *string `json:"CertBeginTime,omitempty" name:"CertBeginTime"`
	// 证书到期时间。

	CertEndTime *string `json:"CertEndTime,omitempty" name:"CertEndTime"`
	// 证书状态。 0:创建中 1:正常 2:已停用 3.已过期 4.创建出错

	CertStatus *uint64 `json:"CertStatus,omitempty" name:"CertStatus"`
	// CLIENT NAME。

	Name *string `json:"Name,omitempty" name:"Name"`
	// SSL-VPN-CLIENT 实例ID。

	SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
	// SSL-VPN-SERVER 实例ID。

	SslVpnServerId *string `json:"SslVpnServerId,omitempty" name:"SslVpnServerId"`
	// 创建CLIENT 状态。 0 创建中 1 创建出错 2 更新中 3 更新出错 4 销毁中 5 销毁出错 6 已连通 7 未知

	State *string `json:"State,omitempty" name:"State"`
	// VPC实例ID。

	VpcId *string `json:"VpcId,omitempty" name:"VpcId"`
}

type SslVpnSever struct {

	// 策略信息

	AccessPolicy []*AccessPolicy `json:"AccessPolicy,omitempty" name:"AccessPolicy"`
	// 是否开启策略控制。0：不开启 1： 开启

	AccessPolicyEnabled *uint64 `json:"AccessPolicyEnabled,omitempty" name:"AccessPolicyEnabled"`
	// 是否开启Client-Hub功能；

	ClientHubEnable *bool `json:"ClientHubEnable,omitempty" name:"ClientHubEnable"`
	// 是否支持压缩。

	Compress *uint64 `json:"Compress,omitempty" name:"Compress"`
	// 创建时间。

	CreateTime *string `json:"CreateTime,omitempty" name:"CreateTime"`
	// EIAM应用ID

	EiamApplicationId *string `json:"EiamApplicationId,omitempty" name:"EiamApplicationId"`
	// 加密算法。

	EncryptAlgorithm *string `json:"EncryptAlgorithm,omitempty" name:"EncryptAlgorithm"`
	// 认证算法。

	IntegrityAlgorithm *string `json:"IntegrityAlgorithm,omitempty" name:"IntegrityAlgorithm"`
	// 本端地址段。

	LocalAddress []*string `json:"LocalAddress,omitempty" name:"LocalAddress"`
	// 客户端最大连接数。

	MaxConnection *uint64 `json:"MaxConnection,omitempty" name:"MaxConnection"`
	// 客户端地址段。

	RemoteAddress *string `json:"RemoteAddress,omitempty" name:"RemoteAddress"`
	// CAM服务提供商Name

	SpName *string `json:"SpName,omitempty" name:"SpName"`
	// SSL VPN服务端监听协议端口

	SslVpnPort *uint64 `json:"SslVpnPort,omitempty" name:"SslVpnPort"`
	// SSL VPN服务端监听协议

	SslVpnProtocol *string `json:"SslVpnProtocol,omitempty" name:"SslVpnProtocol"`
	// SSL-VPN-SERVER 实例ID。

	SslVpnServerId *string `json:"SslVpnServerId,omitempty" name:"SslVpnServerId"`
	// SSL-VPN-SERVER name。

	SslVpnServerName *string `json:"SslVpnServerName,omitempty" name:"SslVpnServerName"`
	// 是否开启SSO认证。1：开启 0： 不开启

	SsoEnabled *uint64 `json:"SsoEnabled,omitempty" name:"SsoEnabled"`
	// SSL-VPN-SERVER 创建状态。 0 创建中 1 创建出错 2 更新中 3 更新出错 4 销毁中 5 销毁出错 6 已连通 7 未知

	State *uint64 `json:"State,omitempty" name:"State"`
	// VPC实例ID.

	VpcId *string `json:"VpcId,omitempty" name:"VpcId"`
	// VPN 实例ID。

	VpnGatewayId *string `json:"VpnGatewayId,omitempty" name:"VpnGatewayId"`
	// SSL-VPN 网关公网IP。

	WanIp *string `json:"WanIp,omitempty" name:"WanIp"`
}

type Tag struct {

	// 标签键

	Key *string `json:"Key,omitempty" name:"Key"`
	// 标签值

	Value *string `json:"Value,omitempty" name:"Value"`
}

type CreateVpnGatewaySslClientRequest struct {
	*tchttp.BaseRequest

	// SSL-VPN-CLIENT实例Name。不可和SslVpnClientNames同时使用。

	SslVpnClientName *string `json:"SslVpnClientName,omitempty" name:"SslVpnClientName"`
	// SSL-VPN-CLIENT实例Name数字。批量创建时使用。不可和SslVpnClientName同时使用。

	SslVpnClientNames []*string `json:"SslVpnClientNames,omitempty" name:"SslVpnClientNames"`
	// SSL-VPN-SERVER 实例ID。

	SslVpnServerId *string `json:"SslVpnServerId,omitempty" name:"SslVpnServerId"`
	// 指定绑定的标签列表

	Tags []*Tag `json:"Tags,omitempty" name:"Tags"`
}

func (r *CreateVpnGatewaySslClientRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *CreateVpnGatewaySslClientRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type CreateVpnGatewaySslClientResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// SSL-VPN client 唯一ID

		SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
		// 异步任务ID。

		TaskId *uint64 `json:"TaskId,omitempty" name:"TaskId"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *CreateVpnGatewaySslClientResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *CreateVpnGatewaySslClientResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type CreateVpnGatewaySslServerRequest struct {
	*tchttp.BaseRequest

	// 是否开启策略访问控制。默认为False

	AccessPolicyEnabled *bool `json:"AccessPolicyEnabled,omitempty" name:"AccessPolicyEnabled"`
	// 是否开启Client-Hub功能；

	ClientHubEnable *bool `json:"ClientHubEnable,omitempty" name:"ClientHubEnable"`
	// 是否支持压缩。当前不支持压缩，默认False。

	Compress *bool `json:"Compress,omitempty" name:"Compress"`
	// 加密算法。可选 'AES-128-CBC','AES-192-CBC', 'AES-256-CBC', 默认AES-128-CBC。

	EncryptAlgorithm *string `json:"EncryptAlgorithm,omitempty" name:"EncryptAlgorithm"`
	// 认证算法。可选 'SHA1'，默认SHA1。

	IntegrityAlgorithm *string `json:"IntegrityAlgorithm,omitempty" name:"IntegrityAlgorithm"`
	// 云端地址（CIDR）列表。

	LocalAddress []*string `json:"LocalAddress,omitempty" name:"LocalAddress"`
	// 客户端地址类型。

	LocalAddressType *string `json:"LocalAddressType,omitempty" name:"LocalAddressType"`
	// 客户端地址网段。

	RemoteAddress *string `json:"RemoteAddress,omitempty" name:"RemoteAddress"`
	// SAML-DATA，开启SSO时传。

	SamlData *string `json:"SamlData,omitempty" name:"SamlData"`
	// CAM服务提供商Name

	SpName *string `json:"SpName,omitempty" name:"SpName"`
	// SSL VPN服务端监听协议端口，默认1194。

	SslVpnPort *int64 `json:"SslVpnPort,omitempty" name:"SslVpnPort"`
	// SSL VPN服务端监听协议。当前仅支持 UDP，默认UDP。

	SslVpnProtocol *string `json:"SslVpnProtocol,omitempty" name:"SslVpnProtocol"`
	// SSL-VPN-SERVER 实例名称，长度不超过60个字节。

	SslVpnServerName *string `json:"SslVpnServerName,omitempty" name:"SslVpnServerName"`
	// 是否开启SSO认证。默认为False。该功能当前需要申请开白使用。

	SsoEnabled *bool `json:"SsoEnabled,omitempty" name:"SsoEnabled"`
	// 指定绑定的标签列表

	Tags []*Tag `json:"Tags,omitempty" name:"Tags"`
	// VPN网关实例ID。

	VpnGatewayId *string `json:"VpnGatewayId,omitempty" name:"VpnGatewayId"`
}

func (r *CreateVpnGatewaySslServerRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *CreateVpnGatewaySslServerRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type CreateVpnGatewaySslServerResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// SSL-VPN-SERVER 唯一ID。

		SslVpnServerId *string `json:"SslVpnServerId,omitempty" name:"SslVpnServerId"`
		// 创建SSL-VPN server 异步任务ID。

		TaskId *int64 `json:"TaskId,omitempty" name:"TaskId"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *CreateVpnGatewaySslServerResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *CreateVpnGatewaySslServerResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DeleteVpnGatewaySslClientRequest struct {
	*tchttp.BaseRequest

	// SSL-VPN-CLIENT 实例ID。不可和SslVpnClientIds同时使用。

	SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
	// SSL-VPN-CLIENT 实例ID列表。批量删除时使用。不可和SslVpnClientId同时使用。

	SslVpnClientIds []*string `json:"SslVpnClientIds,omitempty" name:"SslVpnClientIds"`
}

func (r *DeleteVpnGatewaySslClientRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DeleteVpnGatewaySslClientRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DeleteVpnGatewaySslClientResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// 异步任务ID。

		TaskId *uint64 `json:"TaskId,omitempty" name:"TaskId"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *DeleteVpnGatewaySslClientResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DeleteVpnGatewaySslClientResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DeleteVpnGatewaySslServerRequest struct {
	*tchttp.BaseRequest

	// SSL-VPN-SERVER 实例ID。

	SslVpnServerId *string `json:"SslVpnServerId,omitempty" name:"SslVpnServerId"`
}

func (r *DeleteVpnGatewaySslServerRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DeleteVpnGatewaySslServerRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DeleteVpnGatewaySslServerResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// 异步任务ID。

		TaskId *uint64 `json:"TaskId,omitempty" name:"TaskId"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *DeleteVpnGatewaySslServerResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DeleteVpnGatewaySslServerResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DescribeVpnGatewaySslClientsRequest struct {
	*tchttp.BaseRequest

	// 过滤条件，参数不支持同时指定SslVpnClientIds和Filters。 vpc-id - String - （过滤条件）VPC实例ID形如：vpc-f49l6u0z。 vpn-gateway-id - String - （过滤条件）VPN实例ID形如：vpngw-5aluhh9t。 ssl-vpn-server-id - String - （过滤条件）SSL-VPN-SERVER实例ID形如：vpns-1j2w6xpx。 ssl-vpn-client-id - String - （过滤条件）SSL-VPN-CLIENT实例ID形如：vpnc-3rlxp4nd。 ssl-vpn-client-name - String - （过滤条件）SSL-VPN-CLIENT实例名称。 ssl-vpn-client-inner-ip - String - （过滤条件）SSL-VPN-CLIENT私网IP。

	Filters []*Filter `json:"Filters,omitempty" name:"Filters"`
	// VPN门户网站使用。默认是False。

	IsVpnPortal *bool `json:"IsVpnPortal,omitempty" name:"IsVpnPortal"`
	// 请求对象个数，默认值20。

	Limit *uint64 `json:"Limit,omitempty" name:"Limit"`
	// 偏移量，默认值0。

	Offset *uint64 `json:"Offset,omitempty" name:"Offset"`
	// SSL-VPN-CLIENT实例ID。形如： vpns-1jww3xpx。每次请求的实例的上限为100。参数不支持同时指定SslVpnClientIds和Filters。

	SslVpnClientIds []*string `json:"SslVpnClientIds,omitempty" name:"SslVpnClientIds"`
}

func (r *DescribeVpnGatewaySslClientsRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DescribeVpnGatewaySslClientsRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DescribeVpnGatewaySslClientsResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// SSL-VPN-CLIENT 实例列表。

		SslVpnClientSet []*SslVpnClient `json:"SslVpnClientSet,omitempty" name:"SslVpnClientSet"`
		// 符合条件的实例数量。

		TotalCount *uint64 `json:"TotalCount,omitempty" name:"TotalCount"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *DescribeVpnGatewaySslClientsResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DescribeVpnGatewaySslClientsResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DescribeVpnGatewaySslServersRequest struct {
	*tchttp.BaseRequest

	// 过滤条件，参数不支持同时指定SslVpnServerIds和Filters。 vpc-id - String - （过滤条件）VPC实例ID，形如：vpc-f49l6u0z。 vpn-gateway-id - String - （过滤条件）VPN实例ID，形如：vpngw-5aluhh9t。 vpn-gateway-name - String - （过滤条件）VPN实例名称。 ssl-vpn-server-name - String - （过滤条件）SSL-VPN-SERVER实例名称。 ssl-vpn-server-id - String - （过滤条件）SSL-VPN-SERVER实例ID，形如：vpns-xxx。

	Filters []*FilterObject `json:"Filters,omitempty" name:"Filters"`
	// vpn门户使用。 默认Flase

	IsVpnPortal *bool `json:"IsVpnPortal,omitempty" name:"IsVpnPortal"`
	// 请求对象个数。

	Limit *uint64 `json:"Limit,omitempty" name:"Limit"`
	// 偏移量。

	Offset *uint64 `json:"Offset,omitempty" name:"Offset"`
	// SSL-VPN-SERVER实例ID。形如：vpns-0p4rj60。每次请求的实例的上限为100。参数不支持同时指定SslVpnServerIds和Filters。

	SslVpnServerIds []*string `json:"SslVpnServerIds,omitempty" name:"SslVpnServerIds"`
}

func (r *DescribeVpnGatewaySslServersRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DescribeVpnGatewaySslServersRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DescribeVpnGatewaySslServersResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// SSL-VPN-SERVER 实例详细信息列表。

		SslVpnSeverSet []*SslVpnSever `json:"SslVpnSeverSet,omitempty" name:"SslVpnSeverSet"`
		// 符合条件的实例数量。

		TotalCount *uint64 `json:"TotalCount,omitempty" name:"TotalCount"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *DescribeVpnGatewaySslServersResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DescribeVpnGatewaySslServersResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DisableVpnGatewaySslClientCertRequest struct {
	*tchttp.BaseRequest

	// SSL-VPN-CLIENT 实例ID。不可和SslVpnClientIds同时使用。

	SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
	// SSL-VPN-CLIENT 实例ID列表。批量禁用时使用。不可和SslVpnClientId同时使用。

	SslVpnClientIds []*string `json:"SslVpnClientIds,omitempty" name:"SslVpnClientIds"`
}

func (r *DisableVpnGatewaySslClientCertRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DisableVpnGatewaySslClientCertRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DisableVpnGatewaySslClientCertResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// 异步任务实例ID。

		TaskId *uint64 `json:"TaskId,omitempty" name:"TaskId"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *DisableVpnGatewaySslClientCertResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DisableVpnGatewaySslClientCertResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DownloadVpnGatewaySslClientCertRequest struct {
	*tchttp.BaseRequest

	// VPN门户网站使用。默认False

	IsVpnPortal *bool `json:"IsVpnPortal,omitempty" name:"IsVpnPortal"`
	// SAML Token（SAML令牌）。

	SamlToken *string `json:"SamlToken,omitempty" name:"SamlToken"`
	// SSL-VPN-CLIENT 实例ID。不可以和SslVpnClientIds同时使用。

	SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
	// SSL-VPN-CLIENT 实例ID列表。批量下载时使用。不可以和SslVpnClientId同时使用。

	SslVpnClientIds []*string `json:"SslVpnClientIds,omitempty" name:"SslVpnClientIds"`
}

func (r *DownloadVpnGatewaySslClientCertRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DownloadVpnGatewaySslClientCertRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type DownloadVpnGatewaySslClientCertResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// 是否鉴权成功 只有传入SamlToken 才生效，1为成功，0为失败。

		Authenticated *uint64 `json:"Authenticated,omitempty" name:"Authenticated"`
		// SSL-VPN 客户端配置。

		SslClientConfig []*SslClientConfig `json:"SslClientConfig,omitempty" name:"SslClientConfig"`
		// SSL-VPN 客户端配置。

		SslClientConfigsSet *string `json:"SslClientConfigsSet,omitempty" name:"SslClientConfigsSet"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *DownloadVpnGatewaySslClientCertResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *DownloadVpnGatewaySslClientCertResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type EnableVpnGatewaySslClientCertRequest struct {
	*tchttp.BaseRequest

	// SSL-VPN-CLIENT 实例ID。不可和SslVpnClientIds同时使用。

	SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
	// SSL-VPN-CLIENT 实例ID列表。批量启用时使用。不可和SslVpnClientId同时使用。

	SslVpnClientIds []*string `json:"SslVpnClientIds,omitempty" name:"SslVpnClientIds"`
}

func (r *EnableVpnGatewaySslClientCertRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *EnableVpnGatewaySslClientCertRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type EnableVpnGatewaySslClientCertResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// 异步任务实例ID。

		TaskId *uint64 `json:"TaskId,omitempty" name:"TaskId"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *EnableVpnGatewaySslClientCertResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *EnableVpnGatewaySslClientCertResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type ModifyVpnGatewaySslClientRequest struct {
	*tchttp.BaseRequest

	// SSL-VPN-CLIENT 实例ID

	SslVpnClientId *string `json:"SslVpnClientId,omitempty" name:"SslVpnClientId"`
	// 客户端NAME

	SslVpnClientName *string `json:"SslVpnClientName,omitempty" name:"SslVpnClientName"`
}

func (r *ModifyVpnGatewaySslClientRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *ModifyVpnGatewaySslClientRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type ModifyVpnGatewaySslClientResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *ModifyVpnGatewaySslClientResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *ModifyVpnGatewaySslClientResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type ModifyVpnGatewaySslServerRequest struct {
	*tchttp.BaseRequest

	// 是否开启客户端互通。

	ClientHubEnable *bool `json:"ClientHubEnable,omitempty" name:"ClientHubEnable"`
	// 是否支持压缩。当前不支持压缩。默认False。

	Compress *bool `json:"Compress,omitempty" name:"Compress"`
	// 加密算法。可选 'AES-128-CBC','AES-192-CBC', 'AES-256-CBC', 默认AES-128-CBC。

	EncryptAlgorithm *string `json:"EncryptAlgorithm,omitempty" name:"EncryptAlgorithm"`
	// 认证算法。可选 'SHA1'，默认SHA1。

	IntegrityAlgorithm *string `json:"IntegrityAlgorithm,omitempty" name:"IntegrityAlgorithm"`
	// 本端地址

	LocalAddress []*string `json:"LocalAddress,omitempty" name:"LocalAddress"`
	// 客户端地址类型；

	LocalAddressType *string `json:"LocalAddressType,omitempty" name:"LocalAddressType"`
	// 客户端地址

	RemoteAddress *string `json:"RemoteAddress,omitempty" name:"RemoteAddress"`
	// SAML-DATA

	SamlData *string `json:"SamlData,omitempty" name:"SamlData"`
	// CAM服务提供商Name

	SpName *string `json:"SpName,omitempty" name:"SpName"`
	// SSL VPN服务端监听协议端口。

	SslVpnPort *int64 `json:"SslVpnPort,omitempty" name:"SslVpnPort"`
	// SSL VPN服务端监听协议。当前仅支持 UDP。默认UDP

	SslVpnProtocol *string `json:"SslVpnProtocol,omitempty" name:"SslVpnProtocol"`
	// SSL-VPN SERVER 实例ID

	SslVpnServerId *string `json:"SslVpnServerId,omitempty" name:"SslVpnServerId"`
	// SSL-VPN SERVER NAME

	SslVpnServerName *string `json:"SslVpnServerName,omitempty" name:"SslVpnServerName"`
	// 是否开启SSO认证。默认为False。该功能当前需要申请开白使用。

	SsoEnabled *bool `json:"SsoEnabled,omitempty" name:"SsoEnabled"`
}

func (r *ModifyVpnGatewaySslServerRequest) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *ModifyVpnGatewaySslServerRequest) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type ModifyVpnGatewaySslServerResponse struct {
	*tchttp.BaseResponse

	Response *struct {
		// 异步任务TASKID

		TaskId *int64 `json:"TaskId,omitempty" name:"TaskId"`
		// Unique request ID, returned on each request.
		RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
	} `json:"Response"`
}

func (r *ModifyVpnGatewaySslServerResponse) ToJsonString() string {
	b, _ := json.Marshal(r)
	return string(b)
}

func (r *ModifyVpnGatewaySslServerResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}
